# Generated by Django 2.1.4 on 2020-01-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order_id', models.CharField(max_length=70)),
                ('trade_id', models.CharField(max_length=70)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('app_id', models.CharField(max_length=30)),
                ('seller_id', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '订单记录',
                'verbose_name_plural': '订单记录',
                'db_table': 'api_payment1',
            },
        ),
    ]
