# Generated by Django 2.1.4 on 2020-01-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200106_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='商品小计'),
        ),
    ]
